mspsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_portal.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name='test_login'),
    path('logout/', views.logout, name='test_logout'),
    path('register/', views.register, name = 'register'),
    path('', views.welcome, name='welcome'),
    path('loaderio-158ef98a841f6e5ef17fb5d0b83a3992/', views.test, name = 'test'),

    path('question/<slug:id>/', views.question_list, name='question_list'),
    path('question/<slug:id>/<int:ques_no>/', views.question_list, name='question_list'),

    path('response_save/<int:pk>/<slug:id>/', views.response_save, name='response_save'),
    path('response_save/<int:pk>/<slug:id>/<int:next>/', views.response_save, name='response_save'),

    path('response_savem/<int:pk>/<slug:id>/<int:next>/', views.response_savem, name='response_savem'),
    path('response_savem/<int:pk>/<slug:id>/', views.response_savem, name='response_savem'),

    path('ques_detail_mcq/<slug:id>/',views.ques_detail_mcq,name='ques_detail_mcq'),
    path('ques_detail_mcq/<slug:id>/<int:ques_no>/',views.ques_detail_mcq,name='ques_detail_mcq'),
]

test_portal/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

class Candidate(models.Model):
	firstName = models.CharField(max_length = 25, default = '')
	lastName = models.CharField(max_length = 25, default = '')
	username = models.CharField(max_length = 25, default = '', unique = True)
	email = models.URLField(default = '')
	bitsid = models.CharField(max_length = 20, unique = True)
	contact = models.CharField(max_length = 10, default = '')
	description = models.CharField(max_length = 1000, default = '')
	use_required_attribute = True

	def update_user_profile(sender, instance, created, **kwargs):
		if created:
			Candidate.objects.create(user=instance)
			instance.Candidate.save()

	def __str__(self):
		return self.bitsid

class Exam(models.Model):
	user = models.ForeignKey("Candidate", on_delete=models.CASCADE,)
	logged_in = models.IntegerField(default = 0)
	start_time = models.DateTimeField()
	logged_out = models.IntegerField(default = 0)

	def __str__(self):
		return self.user.bitsid
	
class QuestionSub(models.Model):

	question = models.CharField(max_length=2000, default = '')
	question_image=models.ImageField(null=True, blank= True, upload_to="uploads")

	marks = models.IntegerField(default = 10)
	ques_no = models.IntegerField(null = True)

	def __str__(self):
		return self.question

class QuestionMCQ(models.Model):

	question = models.CharField(max_length=2000, default = '')
	question_image=models.ImageField(null=True, blank= True, upload_to="uploads")
	opt1 = models.CharField(default='', max_length=300)
	opt2 = models.CharField(default='', max_length=300)
	opt3 = models.CharField(default='', max_length=300)
	opt4 = models.CharField(default='', max_length=300)
	marks = models.IntegerField(default = 10)
	ques_no = models.IntegerField(null=True)
	
	ans1 = models.BooleanField(default=False)
	ans2 = models.BooleanField(default=False)
	ans3 = models.BooleanField(default=False)
	ans4 = models.BooleanField(default=False)

	def __str__(self):
		return self.question

class ResponseSub(models.Model):

	user = models.ForeignKey("Candidate", on_delete=models.CASCADE,)
	question = models.ForeignKey("QuestionSub", on_delete=models.CASCADE,)

	free_response = models.TextField(max_length = 3000, blank = True)

	marks = models.IntegerField(default = 0, editable = True)

	def submit(self):
		self.save()

	def __str__(self):
		return self.free_response

	def bitsid(self):
		return self.user.bitsid

	def quesno(self):
		return self.question.ques_no
	
class ResponseMCQ(models.Model):

	user = models.ForeignKey("Candidate", on_delete=models.CASCADE,)
	question = models.ForeignKey("QuestionMCQ", on_delete=models.CASCADE,)

	response1 = models.BooleanField(default=False)
	response2 = models.BooleanField(default=False)
	response3 = models.BooleanField(default=False)
	response4 = models.BooleanField(default=False)

	marks = models.IntegerField(default=0)

	def submit(self):
		self.save()

	def __str__(self):
		return str(self.response1)
	

test_portal/forms.py
from django import forms
from .models import ResponseSub, ResponseMCQ, Candidate,ImageMCQ, ImageSub


class PostForm(forms.ModelForm):

    class Meta:
        model = Candidate
        fields = ('firstName', 'lastName', 'username', 'email', 'bitsid', 'contact', 'description', )

class ImageFormMCQ(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = ImageMCQ
        fields = ('image', )


class ImageFormSub(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = ImageSub
        fields = ('image', )


class GetResponse(forms.ModelForm):

    class Meta:
        model = ResponseSub
        fields = ('free_response',)

class GetResponseMCQ(forms.ModelForm):

    class Meta:
        model = ResponseMCQ
        fields = ('response1', 'response2', 'response3', 'response4',)

test_portal/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Candidate
from django.contrib import auth
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from .forms import PostForm
from .models import QuestionSub, QuestionMCQ
from .models import ResponseSub, ResponseMCQ, Exam
from .forms import GetResponse, GetResponseMCQ
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils import timezone
from django.forms import modelformset_factory
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from .forms import ImageFormMCQ, PostForm, ImageFormSub


# Create your views here.

def welcome(request):
	return render(request,'test_portal/welcome.html')

def test(request):
	return render(request,'test_portal/test.html')

def register(request):
	if request.method == 'POST':
		form = PostForm(request.POST)

		if form.is_valid():
			candidate = Candidate()
			candidate.firstName = form.cleaned_data['firstName']
			candidate.lastName = form.cleaned_data['lastName']
			candidate.username = form.cleaned_data['username']
			candidate.email = form.cleaned_data['email']
			candidate.bitsid = form.cleaned_data['bitsid']
			candidate.contact = form.cleaned_data['contact']
			candidate.description = form.cleaned_data['description']
			candidate.save()
			return redirect('test_login')
		else:
			messages.error(request, form.errors)
	else:
		form = PostForm()
	return render(request, 'test_portal/register.html', {'form': form})

def login(request):
	if request.user.is_authenticated:
		return redirect(ques_detail_mcq, id = request.user.username)

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = auth.authenticate(username=username, password=password)

		# correct username and password login the user
		if user is not None:
			try:
				user1 = Candidate.objects.get(username=username)
				exam = Exam.objects.get(user = user1)
				if exam.logged_out is 1:
					return HttpResponse('You have finished the test')
				else:
					auth.login(request, user)
					return redirect(ques_detail_mcq, id = username)
			except Exam.DoesNotExist:
				exam = Exam()
				exam.user = Candidate.objects.get(username=username)
				exam.start_time = timezone.now()
				exam.logged_in = 1
				exam.save()
				auth.login(request, user)
				return redirect(ques_detail_mcq, id = username)

		else:
			messages.error(request, 'Error wrong username/password')

	return render(request, 'test_portal/login.html')

def instructions(request):
	ques = QuestionMCQ.objects.first()
	context = {'ques': ques}
	return render(request,'test_portal/instructions.html', context)

def ques_detail_mcq(request, ques_no = 1, id = 'a'):
	if not request.user.is_authenticated:
		return redirect('test_login')

	ques_count= QuestionMCQ.objects.order_by("ques_no").count()

	curr_time = timezone.now()

	question = QuestionMCQ.objects.get(ques_no=ques_no)

	user1 = Candidate.objects.get(username=id)
	exam = Exam.objects.get(user = user1)
	time = exam.start_time

	try:
		user = Candidate.objects.get(username=id)
		new = ResponseMCQ.objects.get(user=user, question=QuestionMCQ.objects.get(ques_no = ques_no))
		form = GetResponseMCQ(initial={'response1': new.response1,'response2': new.response2,'response3': new.response3,'response4': new.response4})
		res1 = new.response1
		res2 = new.response2
		res3 = new.response3
		res4 = new.response4
	except ResponseMCQ.DoesNotExist:
		res1 = False
		res2 = False
		res3 = False
		res4 = False
		form = GetResponseMCQ()

	return render(request, 'test_portal/round1.html',{'question': question, 'form': form, 'pksent': ques_no, 'id':id, 'n' : range(1,ques_count+1), 'time' : time,
														   'curr_time' : curr_time, 'response1' : res1,'response2' : res2,'response3' : res3, 'response4' : res4, 'count' : ques_count})

def response_savem(request, pk, next, id = 'a'):
	if request.method == 'POST':
		try:
			response = ResponseMCQ.objects.get(user=Candidate.objects.get(username=id), question=QuestionMCQ.objects.get(ques_no = pk))
		except ResponseMCQ.DoesNotExist:
			response = ResponseMCQ()
		response_rec = GetResponseMCQ(request.POST)
		if response_rec.is_valid():
			response.response1 = response_rec.cleaned_data['response1']
			response.response2 = response_rec.cleaned_data['response2']
			response.response3 = response_rec.cleaned_data['response3']
			response.response4 = response_rec.cleaned_data['response4']
			response.question = QuestionMCQ.objects.get(pk = pk)

			if (response.response1 == response.question.ans1) and (response.response2 == response.question.ans2) and (response.response3 == response.question.ans3) and (response.response4 == response.question.ans4):
				response.marks = response.question.marks

			response.user = Candidate.objects.get(username=id)
			response.save()
			if 'SavePrevious' in request.POST:
				next = pk - 1
				return redirect('ques_detail_mcq', ques_no = next, id = id)

			elif 'SaveNext' in request.POST:
				next = pk + 1
				return redirect('ques_detail_mcq', ques_no = next, id = id)

			elif 'Finish' in request.POST:
				user = Candidate.objects.get(username=id)
				exam = Exam.objects.get(user = user)
				exam.logged_out = 1
				exam.save()
				return redirect('test_logout')

			elif 'Round2' in request.POST:
				return redirect(question_list, id = id)

			else:
				next = int(request.POST['progress-number'])
				return redirect('ques_detail_mcq', ques_no = next, id = id)

	else:
		return HttpResponse('You are not supposed to be here! Go Back! Please!')

	return redirect(ques_detail_mcq, ques_no = next, id = id)

def question_list(request, ques_no = 1, id = 'a'):
	if not request.user.is_authenticated:
		return redirect('test_login')

	ques_count= QuestionSub.objects.order_by("ques_no").count()

	curr_time = timezone.now()

	question = QuestionSub.objects.get(ques_no=ques_no)

	user1 = Candidate.objects.get(username=id)
	exam = Exam.objects.get(user = user1)
	time = exam.start_time

	try:
		user = Candidate.objects.get(username=id)
		new = ResponseSub.objects.get(user=user, question=QuestionSub.objects.get(ques_no = ques_no))
		form = GetResponse(initial={'free_response': new.free_response})
		answer = new.free_response
	except ResponseSub.DoesNotExist:
		answer = ''
		form = GetResponse(initial={'free_response': 'Answer here!'})


	return render(request, 'test_portal/round2.html',{'question': question, 'curr_time' : curr_time, 'form': form, 'time' : time, 'pksent': ques_no, 'id':id, 'n' : range(1,ques_count+1), 'i' : 1, 'response' : answer, 'count' : ques_count})

def response_save(request, pk, next, id = 'a',):
	if request.method == 'POST':
		try:
			response = ResponseSub.objects.get(user=Candidate.objects.get(username=id), question=QuestionSub.objects.get(ques_no = pk))
		except ResponseSub.DoesNotExist:
			response = ResponseSub()
		response_rec = GetResponse(request.POST)
		if response_rec.is_valid():
			response.free_response = response_rec.cleaned_data['free_response']
			response.question = QuestionSub.objects.get(ques_no = pk)
			response.user = Candidate.objects.get(username=id)
			response.save()
			if 'SavePrevious' in request.POST:
				next = pk - 1
				return redirect('question_list', ques_no = next, id = id)

			elif 'SaveNext' in request.POST:
				next = pk + 1
				return redirect('question_list', ques_no = next, id = id)

			elif 'Round1' in request.POST:
				return redirect(ques_detail_mcq, id = id)

			elif 'Finish' in request.POST:
				user = Candidate.objects.get(username=id)
				exam = Exam.objects.get(user = user)
				exam.logged_out = 1
				exam.save()
				return redirect('test_logout')

			else:
				next = int(request.POST['progress-number'])
				return redirect('question_list', ques_no = next, id = id)

	else:
		return HttpResponse('You are not supposed to be here! Go Back! Please!')

	return redirect(question_list, ques_no = next, id = id)

def logout(request):
	auth.logout(request)
	return render(request, 'test_portal/thankYou.html')


@staff_member_required
def postMCQ(request):

    ImageFormSet = modelformset_factory(ImageMCQ,
                                        form=ImageForm, extra=0)
    #'extra' means the number of photos that you can upload   ^
    if request.method == 'POST':

        postForm = PostForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=ImageMCQ.objects.none())


        if postForm.is_valid():
            post_form = postForm.save(commit=False)
            post_form.user = request.user
            post_form.save()

            return HttpResponseRedirect("/")
        else:
            print(postForm.errors, formset.errors)
    else:
        postForm = PostForm()
        formset = ImageFormSet(queryset=ImageMCQ.objects.none())
    return render(request, 'index.html',  {'postForm': postForm, 'formset': formset} )

@staff_member_required
def postSub(request):

    ImageFormSet = modelformset_factory(ImageSub,
                                        form=ImageFormSub, extra=0)
    #'extra' means the number of photos that you can upload   ^
    if request.method == 'POST':

        postForm = PostForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=ImageSub.objects.none())


        if postForm.is_valid():
            post_form = postForm.save(commit=False)
            post_form.user = request.user
            post_form.save()

            return HttpResponseRedirect("/")
        else:
            print(postForm.errors, formset.errors)
    else:
        postForm = PostForm()
        formset = ImageFormSet(queryset=ImageSub.objects.none())
    return render(request, 'index.html',  {'postForm': postForm, 'formset': formset} )

test_portal/templates/test_portal/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  
  <link rel="shortcut icon" href="{% static 'images/MLSA_badge.png' %}" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#000000" />
  <!--
      manifest.json provides metadata used when your web app is installed on a
      user's mobile device or desktop. See https://developers.google.com/web/fundamentals/web-app-manifest/
    -->
  <link rel="manifest" href="{% static '/login/manifest.json' %}" />
  <!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
  <title>MLSA Recruitment Test</title>
  <link rel="shortcut icon" href="{% static '/login/images/MLSA_badge.png' %}" />
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="{% static '/login/index.css' %}">
</head>

<body style="overflow: hidden; background: black">
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root" style="height: 100%">
    <nav class="navbar navbar-expand-md navbar-dark">
      <a class="navbar-brand" href="#">   
        <img id="nav-image" src="{% static '/login/images/MLSA_logo.png' %}" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse navbar-right" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link active" href="#">Login<span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="centered col-11" id="whitebox">
          <div class="container-fluid">
            <div class="row">
              <img src="{% static '/login/images/MLSA_badge.png' %}" alt="" style="width:85px">&nbsp;
              <h1 class="display-4 white-font">Login</h1>
            </div>
          </div>
            {% if messages %}
                <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
          <form style="padding: 10px" id="register" action="" method="post">
      {% csrf_token %}
            <div class="form-group">
              <label for="firstname" class="white-font">Username</label>
              <input type="text" class="form-control" id="firstname" name="username" placeholder="Tom" required>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1" class="white-font">Password</label>
              <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="********" required>
            </div>
            <button type="submit" value="Submit" class="btn btn-primary btn-block btn-lg"
              style="background-color: #5c2d91">Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the <body> tag.

      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    -->
  <canvas id="c"></canvas>
  <script src="{% static '/login/script.js' %}"></script>
</body>

</html>

test_portal/templates/test_portal/logout.html
{% extends 'base.html' %}

{% block content %}

    <script language = "javascript" type = "text/javascript">
	function clearLS() {
		window.localStorage.clear();	
	}
	window.onload = clearLS;
    </script>
    <div class="content">
        <div class="section-inner clearfix">
 
        <p>You have completed your test. Thank you for joining us.</p>
 
        </div>
    </div>
 
{% endblock %}

test_portal/templates/test_portal/round1.html
{% extends 'questions.html' %}
{% load static %}
{% block content %}


<form action="{% url 'response_savem' pksent id pksent %}" method="POST">
    {% csrf_token %}

    <input type="hidden" id="hidden_round" value="1">
    <input type="hidden" id="start_time" value="{{ time|date:"d M Y H:i:s" }}">
    <input type="hidden" id="curr_time" value="{{ curr_time|date:"d M Y H:i:s" }}">
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="nav container-fluid">
            <div class="navbar-logo col-sm-5">
                <img src="{% static '/images/msp-logo.png' %}">
                <span>Microsoft Student Partners | BITS Pilani</span>
            </div>
            <div class="nav-items row col-sm-7">
                <div class="nav-item col-sm-3" id="stage-heading"><p>ROUND 1</p></div>
                <div class="col-sm-5"></div>
                <div class="nav-item col-sm-4" id="stage-2-proceed"><p><button type="submit" name="Round2" onclick="proceedRound2()">Proceed to Round 2 &nbsp;<i class="fa fa-caret-right"></i></button></p></div>
                <button type="submit" name="Finish" id="round1-logout"></button>
            </div>
        </div>
    </nav>

    <div class="main container-fluid row">

        <div class="ques-sel container col-sm-2">
            <p id="ques-sel-title">Progress</p>
            <p id="ques-sel-time">Time left:- <span id="timer-mins"></span>:<span id="timer-secs"></span> s</p>
            <br>
            <div id="button-set">
                {% for i in n %}
                <button type="submit" name="progress-number" value="{{ i }}" class="btn btn-default" onclick="btnClickMCQ()">{{ i }}</button>
                {% endfor %}
            </div>
        </div>

        <div class="content container col-sm-9">
            <div class="row">
                <div class="col-xs-1 nav-arrow left"><button type="submit" name="SavePrevious" onclick="btnClickMCQ()"><i class="fa fa-chevron-left"></i></button></div>
                <div class="col-xs-10 qa">
                    <div class="question">
                        <span class="qnum-span">&nbsp;Question <span id="qnum">{{ pksent }}</span> of <span id="qnum-count">{{ count }}</span>&nbsp;</span>

                        <span class="marks-span">&nbsp;Marks: <span id="marks">{{ question.marks }}</span>&nbsp;</span>
                        <br>
                        <div style="overflow: auto;">
                            <span id="question-p">{{ question.question }}</span>
                        </div>
                    </div>
                    <div class="response">
                        <div class="form-group">
                            <div class="row">
                                <div class="ck-button">
                                    <label>
                                        {% if response1 %}
                                        <input type="checkbox" name="response1" id="id_response1" value="Option 1" class="left-chx" checked hidden><span class="noSelect">{{ question.opt1 }}</span>
                                        {% else %}
                                        <input type="checkbox" name="response1" id="id_response1" value="Option 1" class="left-chx" hidden><span class="noSelect">{{ question.opt1 }}</span>
                                        {% endif %}
                                    </label>
                                </div>

                                <div class="ck-button">
                                    <label>
                                        {% if response2 %}
                                        <input type="checkbox" name="response2" id="id_response2" value="Option 2" class="right-chx" checked hidden><span class="noSelect">{{ question.opt2 }}</span>
                                        {% else %}
                                        <input type="checkbox" name="response2" id="id_response2" value="Option 2" class="right-chx" hidden><span class="noSelect">{{ question.opt2 }}</span>
                                        {% endif %}
                                    </label>
                                </div>

                            </div>
                            <div class="row">

                                <div class="ck-button">
                                    <label>
                                        {% if response3 %}
                                        <input type="checkbox" name="response3" id="id_response3" value="Option 3" class="left-chx" checked hidden><span class="noSelect">{{ question.opt3 }}</span>
                                        {% else %}
                                        <input type="checkbox" name="response3" id="id_response3" value="Option 3" class="left-chx" hidden><span class="noSelect">{{ question.opt3 }}</span>
                                        {% endif %}
                                    </label>
                                </div>

                                <div class="ck-button">
                                    <label>
                                        {% if response4 %}
                                        <input type="checkbox" name="response4" id="id_response4" value="Option 4" class="right-chx" checked hidden><span class="noSelect">{{ question.opt4 }}</span>
                                        {% else %}
                                        <input type="checkbox" name="response4" id="id_response4" value="Option 4" class="right-chx" hidden><span class="noSelect">{{ question.opt4 }}</span>
                                        {% endif %}
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-1 nav-arrow right"><button type="submit" name="SaveNext" onclick="btnClickMCQ()"><i class="fa fa-chevron-right"></i></button></div>
            </div>
        </div>

        <div class="progress-info container-fluid">
            <div class="container row col-sm-12">
                <div class="container col-sm-3">
                    <div class="progress-info-colors" style="background-color: #5bc0de;"></div>
                    <span>Current</span>
                </div>
                <div class="container col-sm-3">
                    <div class="progress-info-colors" style="background-color: #5cb85c;"></div>
                    <span>Answered</span>
                </div>
                <div class="container col-sm-3">
                    <div class="progress-info-colors" style="background-color: #dc3545;"></div>
                    <span>Not Answered</span>
                </div>
                <div class="container col-sm-3">
                    <div class="progress-info-colors" style="background-color: #fff;"></div>
                    <span>Yet to Attempt</span>
                </div>
            </div>
        </div>

    </div>

</form>

{% endblock %}